### ISSUE TITLE
三节点xpoa联盟链网络，其中一个节点front服务不可用时，区块链网络无法继续出块

### ISSUE THREAD

**Issue by CodeCmn** [xuperchain/xuper-front#14]
测试发现三节点xpoa联盟链网络，有一个节点front服务挂掉后，其他另外节点xchain持续报错，且网络内区块不再增长，网络不可用。

**Comment by CodeCmn** [comment]
staticNodes:
  xuper: # 这里就是 xfront 端口配置。
    - "192.168.1.120:57101"
    - "192.168.1.121:57101"
    - "192.168.1.101:57101"
其中一个节点的front宕机后，网络就不可用了。
xchain   xfront  都是master分支上的最新代码。

**Comment by superlitian** [comment]
XPOA是带Chained-BFT组件的，BFT容错大概是n≥3f+1，4节点允许1个不work，3节点不允许，系统的失效节点数量不超过系统节点的1/3

**Comment by CodeCmn** [comment]
好的  我们试一下，谢谢。

**Comment by CodeCmn** [comment]
> 
非常感谢，问题已解决。

**Comment by CodeCmn** [comment]
> 
非常感谢，问题已解决。
